### ISSUE TITLE
please write requests for insults here...

### ISSUE THREAD

**Issue by dpvb** [dpvb/meep-bot#4]
put your insult requests here.

**Comment by d-lee-te** [comment]
i bet u go to bed w/ socks on

**Comment by d-lee-te** [comment]
i bet you still display your kindergarten participation trophies

**Comment by d-lee-te** [comment]
ur feet stink

**Comment by d-lee-te** [comment]
ur parents still leash u when they go out w/ u?

**Comment by d-lee-te** [comment]
ur not funny

**Comment by d-lee-te** [comment]
still sippin appy juice????

**Comment by d-lee-te** [comment]
bro gets starbucks with their rewards

**Comment by d-lee-te** [comment]
i bet ur sticky notes aren't even sticky

**Comment by d-lee-te** [comment]
probably sleeps with fan on ngl

**Comment by d-lee-te** [comment]
probably couldn't rawdog a 12 hr flight

**Comment by d-lee-te** [comment]
u need a fork for your chopsticks?

**Comment by d-lee-te** [comment]
i bet u only clean ur bathroom once a month

**Comment by d-lee-te** [comment]
probably puts on underwear after the pants

**Comment by d-lee-te** [comment]
i bet u like cookies over brownies

**Comment by d-lee-te** [comment]
this guy got a headphone dent for sure

**Comment by d-lee-te** [comment]
*teleports behind u*

**Comment by d-lee-te** [comment]
i bet u thought the dress was white and not blue

**Comment by d-lee-te** [comment]
i bet ur not even sad hamster

**Comment by d-lee-te** [comment]
bro witnessed and saw square

**Comment by d-lee-te** [comment]
cope, seethe, mald

**Comment by d-lee-te** [comment]
i bet u still got riot client and vanguard on startup

**Comment by d-lee-te** [comment]
u let rrisky out mow you?????

**Comment by d-lee-te** [comment]
bro is probably a g2 fan

**Comment by d-lee-te** [comment]
prolly a country music enjoyer this one, yikers

**Comment by d-lee-te** [comment]
just do it, more like, just can't do it

**Comment by d-lee-te** [comment]
u singlehandedly made "Rise" "Fall"

**Comment by d-lee-te** [comment]
bro is vampire but no fangs

**Comment by d-lee-te** [comment]
all yap no bite

**Comment by d-lee-te** [comment]
not a grass enjoyer i c

**Comment by d-lee-te** [comment]
whens the last time sunlight touched u

**Comment by d-lee-te** [comment]
bro is a Nat 1

**Comment by d-lee-te** [comment]
bro has 2 guest houses

**Comment by d-lee-te** [comment]
bro has 4 monitors

**Comment by d-lee-te** [comment]
probably watches tiktok in landscape

**Comment by d-lee-te** [comment]
i bet u scream chat clip that

**Comment by d-lee-te** [comment]
probably uses clip software

**Comment by d-lee-te** [comment]
bro screams chat, chat, chat

**Comment by d-lee-te** [comment]
bro probably has a job ngl

**Comment by d-lee-te** [comment]
bro is probably in a loving and caring relationship

**Comment by d-lee-te** [comment]
9pm, past your bedtime
